services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Juani2214
      - N8N_HOST=n8n-docker-zmlq.onrender.com
      - N8N_PORT=5678
      - WEBHOOK_URL=https://n8n-docker-zmlq.onrender.com/
    volumes:
      - ./n8n_data:/home/node/.n8n          
